<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="Krishnavenis-MacBook-Air.local" name="TSuites.Shopping" tests="5" failures="1" timestamp="2021-11-21T17:08:55 IST" time="18.081" errors="0">
  <testcase name="ValidUserLoginCheck" time="5.654" classname="TSuites.Shopping"/>
  <system-out/>
  <testcase name="MedAddCart" time="12.427" classname="TSuites.Shopping">
    <failure type="java.lang.AssertionError" message="expected [http://localhost:8080/medicare/cart/show] but found [driver.getCurrentUrl();]">
      <![CDATA[java.lang.AssertionError: expected [http://localhost:8080/medicare/cart/show] but found [driver.getCurrentUrl();]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at pageobjects.AddCart.AddMedicine(AddCart.java:53)
at TSuites.Shopping.MedAddCart(Shopping.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MedAddCart -->
  <system-out/>
  <testcase name="InValidUserLoginCheck" classname="TSuites.Shopping">
    <skipped/>
  </testcase> <!-- InValidUserLoginCheck -->
  <system-out/>
  <testcase name="InValidPasswordLoginCheck" classname="TSuites.Shopping">
    <skipped/>
  </testcase> <!-- InValidPasswordLoginCheck -->
  <system-out/>
  <testcase name="ViewProductList" classname="TSuites.Shopping">
    <skipped/>
  </testcase> <!-- ViewProductList -->
  <system-out/>
</testsuite> <!-- TSuites.Shopping -->
